# [Docker](https://docs.docker.com/):
# - `docker-compose up`.
# - `docker-compose down`.

# [podman](https://podman.io/) - [podman-compose](https://github.com/containers/podman-compose):
# - `podman-compose up`.
# - `podman-compose down`.

services:
  db:
    image: postgres:17.2
    container_name: PostgreSQL
    restart: on-failure
    shm_size: 512mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: database_name
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
