# [Docker](https://docs.docker.com/):
# - `docker-compose up`.
# - `docker-compose down`.

# [podman](https://podman.io/) - [podman-compose](https://github.com/containers/podman-compose):
# - `podman-compose up`.
# - `podman-compose down`.

services:
  db:
    image: mariadb:11.6.2-ubi9
    container_name: MariaDB
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database_name
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
